### ISSUE TITLE
wrong article name/missing article

### ISSUE THREAD

**Issue by Mxrk** [MicrosoftDocs/bot-docs.de-DE#2]
Hi, I noticed a problem while trying to edit the following article:
https://docs.microsoft.com/de-de/azure/bot-service/bot-builder-deploy-az-cli

If you try to use the edit button on the page, you will get an error (404) because the name is wrong(?) or the article is missing.

**Comment by CeciAc** [comment]
Hello, @Mxrk 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---
@SunnyDeng @ishasahni1 can you please take a look on this?

**Comment by ishasahni1** [comment]
Hello @Mxrk 

Thank you for your feedback. We found that there is some technical issue on our end, due to which the sync is not working as expected. Which led to a 404 error. We are working on addressing this issue on our end.

Kind Regards,
Isha

@CeciAc
