### ISSUE TITLE
Example code function "logMessageText" warnings

### ISSUE THREAD

**Issue by chrismade** [MicrosoftDocs/bot-docs.de-DE#3]
Can someone pls have a look on the example code function "logMessageText" on page:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?tabs=javascript&view=azure-bot-service-4.0
when following the instructions:

build an echo bot using botbuilder:

```
yo botbuilder -N "botlog02" -D "test options to log conversations" -T echo
```
test --> everything is as expected when running locally on bot emulator 4.4.0

next copy and paste "bot.js" from its first appearance at the very top of the page and overwrite the existing "bot.js" - then testing again, you will see this warning (which says it will become an breaking error in the future so I guess this should be fixed):

```
(node:14516) UnhandledPromiseRejectionWarning: TypeError: Cannot perform 'set' on a proxy that has been revoked
    at adapter.sendActivities.then (D:\daten\bots\botlog02\botlog-02\node_modules\botbuilder-core\lib\turnContext.js:176:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a
catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
When you comment out the call of function "logMessageText" in "this.onMessage" then no warning appears - 

This issue appears even before you proceed and start working with CosmosDB or blob storage - and it will not go away with any of these enhancements.

Usually I don't care much on warnings in example code as it is usually a trade off to make code lean to see what matters - and to catch all imaginable scenarios which obviously make the code more complex.

What worries me even more is that I cannot fix it myself - I can comment out all "turnContext.sendActivity" inside the function which makes the warning(s) go away  - but I also would like to understand why the warning comes up at all - Good news: The "turnContext.sendActivity" inside the function are not essential - it is rather for a better understanding to info the user what is going on - so if there is not fix for this issue at least make a box into the doc page that users should ignore the warning and remove all "turnContext.sendActivity" before they move towards production
  

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Direktes Schreiben in den Speicher - Bot Service](https://docs.microsoft.com/de-de/azure/bot-service/bot-builder-howto-v4-storage?tabs=javascript&view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs.de-DE/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by chrismade** [comment]
my node version is:
```
node --version
v10.14.0
```

**Comment by CeciAc** [comment]
Hello, @chrismade

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/bot-docs/issues/1164

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
